#!/bin/bash

set -e

function shut_down() {
    echo "Shutting down"
}

trap "shut_down" SIGKILL SIGTERM SIGHUP SIGINT EXIT

mkdir -p ${SONATYPE_WORK}

cd ${NEXUS_HOME}

# If we were started with NEXUS_UID set to something else than the
# initial 200, then we have to modify the uid/gid of user nexus and
# change the ownership of all files

previous_uid=$(stat -c %u ${NEXUS_HOME})
if [[ $previous_uid != ${NEXUS_UID} ]] ; then
    echo
    echo "The owner of $NEXUS_HOME (UID $previous_uid) is different than the current NEXUS_UID (= $NEXUS_UID)"
    echo
    echo "I will change the ownership (might take forever)."
    echo
    sed -i -e "s|^nexus.*|nexus:x:${NEXUS_UID}:${NEXUS_GID}::/opt/nexus:/bin/false|" /etc/passwd
    sed -i -e "s|^nexus.*|nexus:x:${NEXUS_GID}:|" /etc/group
    chown -R nexus:nexus /opt/nexus
    chown -R nexus:nexus ${SONATYPE_WORK}
else
    chown nexus:nexus ${SONATYPE_WORK}
fi

# without '-b' start-stop-daemon stays in foreground
start-stop-daemon -c nexus -x ${NEXUS_HOME}/bin/nexus -S -- run
